# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'horarios.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Horarios(object):
    def setupUi(self, Horarios):
        Horarios.setObjectName("Horarios")
        Horarios.resize(969, 679)
        self.centralwidget = QtWidgets.QWidget(Horarios)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 951, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.Editar = QtWidgets.QWidget()
        self.Editar.setObjectName("Editar")
        self.tableWidget = QtWidgets.QTableWidget(self.Editar)
        self.tableWidget.setGeometry(QtCore.QRect(130, 250, 191, 301))
        self.tableWidget.setRowCount(9)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.Editar)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 20, 341, 221))
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.checkBox = QtWidgets.QCheckBox(self.Editar)
        self.checkBox.setGeometry(QtCore.QRect(350, 310, 141, 22))
        self.checkBox.setObjectName("checkBox")
        self.pb_save = QtWidgets.QPushButton(self.Editar)
        self.pb_save.setGeometry(QtCore.QRect(370, 431, 85, 27))
        self.pb_save.setObjectName("pb_save")
        self.groupBox = QtWidgets.QGroupBox(self.Editar)
        self.groupBox.setGeometry(QtCore.QRect(580, 150, 241, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 109, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(11, 70, 41, 17))
        self.label_4.setObjectName("label_4")
        self.de_begin = QtWidgets.QDateEdit(self.groupBox)
        self.de_begin.setGeometry(QtCore.QRect(70, 60, 110, 27))
        self.de_begin.setCalendarPopup(True)
        self.de_begin.setDate(QtCore.QDate(2018, 1, 2))
        self.de_begin.setObjectName("de_begin")
        self.de_end = QtWidgets.QDateEdit(self.groupBox)
        self.de_end.setGeometry(QtCore.QRect(70, 100, 110, 27))
        self.de_end.setCalendarPopup(True)
        self.de_end.setDate(QtCore.QDate(2018, 10, 11))
        self.de_end.setObjectName("de_end")
        self.pb_configure = QtWidgets.QPushButton(self.groupBox)
        self.pb_configure.setGeometry(QtCore.QRect(70, 140, 85, 27))
        self.pb_configure.setObjectName("pb_configure")
        self.pb_calculate = QtWidgets.QPushButton(self.Editar)
        self.pb_calculate.setGeometry(QtCore.QRect(370, 391, 85, 27))
        self.pb_calculate.setObjectName("pb_calculate")
        self.pb_update = QtWidgets.QPushButton(self.Editar)
        self.pb_update.setGeometry(QtCore.QRect(370, 350, 85, 27))
        self.pb_update.setObjectName("pb_update")
        self.pb_clear = QtWidgets.QPushButton(self.Editar)
        self.pb_clear.setGeometry(QtCore.QRect(370, 470, 85, 27))
        self.pb_clear.setObjectName("pb_clear")
        self.tabWidget.addTab(self.Editar, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 70, 921, 361))
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(40, 25, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(230, 24, 54, 17))
        self.label_2.setObjectName("label_2")
        self.de_from = QtWidgets.QDateEdit(self.tab_2)
        self.de_from.setGeometry(QtCore.QRect(80, 20, 110, 27))
        self.de_from.setCalendarPopup(True)
        self.de_from.setDate(QtCore.QDate(2018, 3, 15))
        self.de_from.setObjectName("de_from")
        self.de_to = QtWidgets.QDateEdit(self.tab_2)
        self.de_to.setGeometry(QtCore.QRect(270, 20, 110, 27))
        self.de_to.setCalendarPopup(True)
        self.de_to.setDate(QtCore.QDate(2018, 3, 15))
        self.de_to.setObjectName("de_to")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(500, 474, 91, 17))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(493, 519, 101, 17))
        self.label_6.setObjectName("label_6")
        self.le_positive = QtWidgets.QLineEdit(self.tab_2)
        self.le_positive.setGeometry(QtCore.QRect(600, 470, 113, 27))
        self.le_positive.setObjectName("le_positive")
        self.le_negative = QtWidgets.QLineEdit(self.tab_2)
        self.le_negative.setGeometry(QtCore.QRect(600, 514, 113, 27))
        self.le_negative.setObjectName("le_negative")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(123, 474, 101, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(133, 520, 91, 17))
        self.label_8.setObjectName("label_8")
        self.le_he = QtWidgets.QLineEdit(self.tab_2)
        self.le_he.setGeometry(QtCore.QRect(223, 470, 113, 27))
        self.le_he.setObjectName("le_he")
        self.le_absent = QtWidgets.QLineEdit(self.tab_2)
        self.le_absent.setGeometry(QtCore.QRect(223, 514, 113, 27))
        self.le_absent.setObjectName("le_absent")
        self.pb_load = QtWidgets.QPushButton(self.tab_2)
        self.pb_load.setGeometry(QtCore.QRect(420, 20, 85, 27))
        self.pb_load.setObjectName("pb_load")
        self.tabWidget.addTab(self.tab_2, "")
        Horarios.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Horarios)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 27))
        self.menubar.setObjectName("menubar")
        Horarios.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Horarios)
        self.statusbar.setObjectName("statusbar")
        Horarios.setStatusBar(self.statusbar)

        self.retranslateUi(Horarios)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Horarios)

    def retranslateUi(self, Horarios):
        _translate = QtCore.QCoreApplication.translate
        Horarios.setWindowTitle(_translate("Horarios", "Horários"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Horarios", "Entrada1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Horarios", "Saida1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Horarios", "Entrada2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Horarios", "Saida2"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Horarios", "Entrada3"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Horarios", "Saida3"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Horarios", "Hora Extra"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Horarios", "Ausência"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Horarios", "Comentário"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Horarios", "Valores"))
        self.checkBox.setText(_translate("Horarios", "Almoço no CNPEM"))
        self.pb_save.setText(_translate("Horarios", "Salvar"))
        self.groupBox.setTitle(_translate("Horarios", "Compensação de pontes e feriados"))
        self.label_5.setText(_translate("Horarios", "Fim:"))
        self.label_4.setText(_translate("Horarios", "Início:"))
        self.de_begin.setDisplayFormat(_translate("Horarios", "dd/MM/yyyy"))
        self.de_end.setDisplayFormat(_translate("Horarios", "dd/MM/yyyy"))
        self.pb_configure.setText(_translate("Horarios", "Configurar"))
        self.pb_calculate.setText(_translate("Horarios", "Calcular"))
        self.pb_update.setText(_translate("Horarios", "Hoje"))
        self.pb_clear.setText(_translate("Horarios", "Limpar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Editar), _translate("Horarios", "Editar"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Horarios", "Entrada1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Horarios", "Saida1"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Horarios", "Entrada2"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Horarios", "Saida2"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Horarios", "Entrada3"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Horarios", "Saida3"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Horarios", "Hora Extra"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Horarios", "Ausência"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Horarios", "Comentário"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Horarios", "Almoço"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("Horarios", "Compensação"))
        self.label.setText(_translate("Horarios", "De:"))
        self.label_2.setText(_translate("Horarios", "Até:"))
        self.de_from.setDisplayFormat(_translate("Horarios", "dd/MM/yyyy"))
        self.de_to.setDisplayFormat(_translate("Horarios", "dd/MM/yyyy"))
        self.label_3.setText(_translate("Horarios", "Horas Positivas:"))
        self.label_6.setText(_translate("Horarios", "Horas Negativas:"))
        self.label_7.setText(_translate("Horarios", "Hora Extra Total:"))
        self.label_8.setText(_translate("Horarios", "Ausência Total:"))
        self.pb_load.setText(_translate("Horarios", "Carregar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Horarios", "Visualizar"))

